packages:
  - packages/*

allowBuilds:
  core-js-pure: false
  dtrace-provider: false
  re2: false

catalog:
  typescript: 7.0.2
  oxlint: 1.75.0
  oxfmt: 0.59.0
  vite: 8.1.5
  vitest: 4.1.10

ignoredBuiltDependencies:
  - core-js-pure
  - dtrace-provider
  - re2

verifyDepsBeforeRun: false
